// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9i5Sntvs79JkoK4QGi5vMGxsFaNiW21o',
    appId: '1:250811921383:web:d64f7dc961f1402b028342',
    messagingSenderId: '250811921383',
    projectId: 'ulenguage',
    authDomain: 'ulenguage.firebaseapp.com',
    storageBucket: 'ulenguage.firebasestorage.app',
    measurementId: 'G-B3WKR9FD3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzWrjT8pxL_yRjfURIaazi3SqBElc_oIY',
    appId: '1:250811921383:android:98bf58c7b2f785d5028342',
    messagingSenderId: '250811921383',
    projectId: 'ulenguage',
    storageBucket: 'ulenguage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDTmHJfIazehss2-Iv-6YPmLrRBgCxk50',
    appId: '1:250811921383:ios:1d7b9070a38ca97b028342',
    messagingSenderId: '250811921383',
    projectId: 'ulenguage',
    storageBucket: 'ulenguage.firebasestorage.app',
    iosClientId: '250811921383-cbsingbvqsgprahlkngakltkasm18ibk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulenguageProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDTmHJfIazehss2-Iv-6YPmLrRBgCxk50',
    appId: '1:250811921383:ios:1d7b9070a38ca97b028342',
    messagingSenderId: '250811921383',
    projectId: 'ulenguage',
    storageBucket: 'ulenguage.firebasestorage.app',
    iosClientId: '250811921383-cbsingbvqsgprahlkngakltkasm18ibk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulenguageProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9i5Sntvs79JkoK4QGi5vMGxsFaNiW21o',
    appId: '1:250811921383:web:548723d878bfab47028342',
    messagingSenderId: '250811921383',
    projectId: 'ulenguage',
    authDomain: 'ulenguage.firebaseapp.com',
    storageBucket: 'ulenguage.firebasestorage.app',
    measurementId: 'G-693S3YJR9J',
  );
}
